### ISSUE TITLE
Xmn page for Gencon GC policy need to be updated.

### ISSUE THREAD

**Issue by smuluka** [eclipse-openj9/openj9-docs#852] opened 2021-09-30 12:47 UTC
**Page containing the error:**
https://www.ibm.com/docs/en/sdk-java-technology/8?topic=options-xmn
*www.eclipse.org/openj9/docs/*

**Describe the error and the update needed:**
https://www.ibm.com/docs/en/sdk-java-technology/8?topic=options-xmn
Above page says Xmn will be ignored for any other GC policies other than Gencon.
Xmn / -Xmns / -Xmnx
Sets the initial and maximum size of the nursery area when using the gencon garbage collection (GC) policy (-Xgcpolicy:gencon). These options are ignored if they are used with any other GC policy.
BUT Xmn is an accepted argument for balanced GC policy.
 https://www.ibm.com/docs/en/sdk-java-technology/8?topic=options-xgcpolicy#balanced-64-bit-only
Gencon page need to be updated to include the text "except for Balanced GC policy"

Thank you,
Saritha

**Comment by dmitripivkine** [comment] 2021-09-30 12:54
duplicate of https://github.com/eclipse-openj9/openj9-docs/pull/841

**Closed by dmitripivkine** 2021-09-30 12:54 UTC
