### ISSUE TITLE
Document JITServer server-side AOT caching

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9-docs#953] opened 2022-06-23 10:15 UTC
**Issue or pull request number:**
*https://github.com/eclipse-openj9/openj9/issues/12153*

**Overview:**
*JITServer added support for caching AOT compiled method bodies. When a JVM client asks for an AOT compilation, if the requested method is present in the server-side cache, the JITServer can avoid the overhead of compiling this method again. This improves the CPU utilization of JITServer and of the cluster as a whole. New options were added to enable this feature.*

**Release target:**
*Eclipse OpenJ9 0.33.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux X|P|Z*

**New command line options:**
`-XX:[+|-]JITServerUseAOTCache`  enabled/disables server-side AOT caching

**Comment by Sreekala-Gopakumar** [comment] 2022-07-01 13:24
@mpirvu, 
Updated the documents JITServer technology, JITServer tuning and practical considerations, What's new in version 0.33.0 topics. 
Added 3 new topics - -XX:[+|-]JITServerMetrics, -XX:JITServerMetricsPort, -XX:[+|-]JITServerUseAOTCache.

Could you please review the same and let me know if changes are required.

Also, following needs clarifications:

The “JITServer technology” topic (https://www.eclipse.org/openj9/docs/jitserver/) currently doesn't talk about AOT at all but this new feature is only about AOT caching so presumably JITServer could do AOT compilation before? In which case…

- Was JITServer’s ability to AOT-compile code there since JITServer was first created or was it added later? It's not mentioned as a new capability in any of our What's New topics so perhaps it was missed as a new capability?

- Should this topic mention AOT everywhere that JIT is mentioned? Eg "JITServer technology decouples the JIT and AOT compilers from the VM and lets the compilers run remotely in their own processes.", "This mechanism prevents your Java application suffering possible negative effects due to CPU and memory consumption caused by JIT and AOT compilation.", "You might want to try this technology if the following criteria are met […] Your Java application is required to compile many methods using JIT or AOT in a relatively short time, The application is running in an environment with limited CPU or memory, which can worsen interference from the JIT or AOT compilers." etc

Thanks!

**Comment by mpirvu** [comment] 2022-07-06 03:59
@Sreekala-Gopakumar 

> Was JITServer’s ability to AOT-compile code there since JITServer was first created or was it added later?

The ability to AOT compile was present in JITServer since its inception.

> Should this topic mention AOT everywhere that JIT is mentioned?

No, I don't think so. To be technically accurate, there is a single compiler, the JIT compiler, which can perform both AOT and regular JIT compilations.

**Comment by doveye** [comment] 2022-07-28 10:21
Because the recent changes were editorial (approval had already been given so technical accuracy should be ok) and GA is imminent, I merged the PR. Feel free to add further comments if other things are spotted, and we can address them later.

**Closed by doveye** 2022-07-28 10:21 UTC
